exec-once = /nix/store/5gln2rkcjx93cr5x0rr3wqrxjdmshd2f-dbus-1.16.2/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
$menu=fuzzel
$mod=SUPER
$terminal=alacritty
animations {
  enabled=false
}

bind=$mod, return, exec, $terminal
bind=$mod_SHIFT, Q, killactive,
bind=$mod_SHIFT, E, exit,
bind=$mod, SPACE, togglefloating,
bind=$mod, P, exec, $menu
bind=$mod, left, movefocus, l
bind=$mod, right, movefocus, r
bind=$mod, up, movefocus, u
bind=$mod, down, movefocus, d
bind=$mod_SHIFT, left, swapwindow, l
bind=$mod_SHIFT, right, swapwindow, r
bind=$mod_SHIFT, up, swapwindow, u
bind=$mod_SHIFT, down, swapwindow, d
bind=$mod, 1, workspace, 1
bind=$mod, 2, workspace, 2
bind=$mod, 3, workspace, 3
bind=$mod, 4, workspace, 4
bind=$mod, 5, workspace, 5
bind=$mod, 6, workspace, 6
bind=$mod, 7, workspace, 7
bind=$mod, 8, workspace, 8
bind=$mod, 9, workspace, 9
bind=$mod, 0, workspace, 10
bind=$mod_SHIFT, 1, movetoworkspacesilent, 1
bind=$mod_SHIFT, 2, movetoworkspacesilent, 2
bind=$mod_SHIFT, 3, movetoworkspacesilent, 3
bind=$mod_SHIFT, 4, movetoworkspacesilent, 4
bind=$mod_SHIFT, 5, movetoworkspacesilent, 5
bind=$mod_SHIFT, 6, movetoworkspacesilent, 6
bind=$mod_SHIFT, 7, movetoworkspacesilent, 7
bind=$mod_SHIFT, 8, movetoworkspacesilent, 8
bind=$mod_SHIFT, 9, movetoworkspacesilent, 9
bind=$mod_SHIFT, 0, movetoworkspacesilent, 10

bindm=$mod, mouse:272, movewindow
bindm=$mod, mouse:273, resizewindow

decoration {
  blur {
    enabled=true
    passes=1
    size=3
    vibrancy=0.169600
  }
  active_opacity=1.000000
  inactive_opacity=1.000000
  rounding=10
}

dwindle {
  preserve_split=true
}

general {
  allow_tearing=false
  border_size=1
  gaps_in=5
  gaps_out=5
  resize_on_border=false
}

input {
  touchpad {
    natural_scroll=false
  }
  follow_mouse=1
  kb_layout=us
  sensitivity=0
}

misc {
  disable_hyprland_logo=false
  force_default_wallpaper=-1
}

monitorv2 {
  output=
  mode=preffered
  position=auto
  scale=1.0
}

windowrule {
  name=suppress windows' event
  match:class=*
  suppress_event=maximize
}
